name: 🐧 Linux Builds
on:
  workflow_call:
    inputs:
      base-branch:
        description: 'Base branch to use for the builds'
        type: string
      lto:
        description: 'LTO mode. Options: "none", "thin", "full"'
        type: string
      repo:
        description: 'Repository to use for the build'
        type: string
      tag:
        description: 'Tag to use for the build'
        type: string
      module_flags:
        description: 'Extra module flags, e.g. module_webm_enabled=no'
        type: string
      template_module_flags:
        description: 'Extra module flags for template build, e.g. module_webm_enabled=no'
        type: string
      use_encryption_key:
        description: 'Whether to use the encryption key for the build (if available)'
        type: string

# Global Settings
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: ${{ inputs.base-branch }}
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  TSAN_OPTIONS: suppressions=misc/error_suppressions/tsan.txt
  UBSAN_OPTIONS: suppressions=misc/error_suppressions/ubsan.txt

jobs:
  build-linux:
    # Use AlmaLinux 8 to increase portability of Linux artifacts.
    runs-on: ubuntu-latest
    container: almalinux:8
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor, arch=x86_64)
            target: editor
            scons-flags: arch=x86_64
            scons-mono-flags: ''
            build-mono: false

          - name: Template (target=template_debug, arch=x86_64)
            target: template_debug
            scons-flags: arch=x86_64
            scons-mono-flags: ''
            build-mono: false

          - name: Template (target=template_release, arch=x86_64)
            target: template_release
            scons-flags: arch=x86_64
            scons-mono-flags: ''
            build-mono: false

          - name: Editor Mono (target=editor arch=x86_64)
            target: editor
            scons-flags: arch=x86_64 module_mono_enabled=yes mono_static=yes
            scons-mono-flags: ''
            build-mono: true

          - name: Template Mono (target=template_debug arch=x86_64)
            target: template_debug
            scons-flags: arch=x86_64 module_mono_enabled=yes mono_static=yes
            scons-mono-flags: ''
            build-mono: true

          - name: Template Mono (target=template_release arch=x86_64)
            target: template_release
            scons-flags: arch=x86_64 module_mono_enabled=yes mono_static=yes
            scons-mono-flags: ''
            build-mono: true

    steps:
      - name: Setup Linux environment
        run: |
          rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled powertools
          dnf update -y
          dnf install -y git pkgconfig tar bzip2 wget file
          if [[ "${{ matrix.target }}" == "editor" ]]; then
            dnf install -y gettext
          fi

      - name: Set architecture for dependencies
        run: |
          if [[ "${{ matrix.scons-flags }}" == *"arch=x86_64"* ]]; then
            echo "DEP_ARCH=x86_64" >> $GITHUB_ENV
            echo "BIN_ARCH=x86_64" >> $GITHUB_ENV
          elif [[ "${{ matrix.scons-flags }}" == *"arch=x86_32"* ]]; then
            echo "DEP_ARCH=i686" >> $GITHUB_ENV
            echo "BIN_ARCH=x86_32" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          dnf install -y libatomic.${{ env.DEP_ARCH }} libatomic-static.${{ env.DEP_ARCH }} wayland-devel.${{ env.DEP_ARCH }} clang.${{ env.DEP_ARCH }} lld.${{ env.DEP_ARCH }}
          ln -s /usr/lib/gcc/${{ env.DEP_ARCH }}-redhat-linux/8/libatomic.a /usr/lib/libatomic.a
          wget https://github.com/godotengine/buildroot/releases/download/godot-2023.08.x-4/${{ env.DEP_ARCH }}-godot-linux-gnu_sdk-buildroot.tar.bz2
          tar -xjf ${{ env.DEP_ARCH }}-godot-linux-gnu_sdk-buildroot.tar.bz2 -C /opt
          /opt/${{ env.DEP_ARCH }}-godot-linux-gnu_sdk-buildroot/relocate-sdk.sh
          export PATH=/opt/${{ env.DEP_ARCH }}-godot-linux-gnu_sdk-buildroot/bin:$PATH
          echo "PATH=/opt/${{ env.DEP_ARCH }}-godot-linux-gnu_sdk-buildroot/bin:$PATH" >> $GITHUB_PATH
          if [[ "${{ matrix.target }}" == "editor" ]]; then
            echo "MODULEFLAGS=${{ inputs.module_flags }}" >> $GITHUB_ENV
          else
            echo "MODULEFLAGS=${{ inputs.template_module_flags }}" >> $GITHUB_ENV
          fi

      - name: Install .NET SDK
        if: matrix.build-mono
        run: |
          dnf install -y dotnet-sdk-8.0

      - name: Free disk space on runner
        run: |
          echo "Disk usage before:" && df -h
          rm -rf /usr/local/lib/android
          echo "Disk usage after:" && df -h

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.tag }}
          submodules: recursive

      - name: Export Encryption Key
        if: ${{ inputs.use_encryption_key == 'true' }}
        run: echo "SCRIPT_AES256_ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> $GITHUB_ENV

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: linux-${{ matrix.target }}-${{ matrix.scons-flags }}-${{ inputs.lto }}
        continue-on-error: true

      - name: Editor compilation for glue
        uses: ./.github/actions/godot-build
        if: matrix.build-mono
        with:
          scons-flags: ${{ env.SCONSFLAGS }} ${{ matrix.scons-flags }} ${{ matrix.scons-mono-flags }} ${{ inputs.lto }} ${{ env.MODULEFLAGS }}
          platform: linuxbsd
          target: ${{ matrix.target }}

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} ${{ matrix.scons-flags }} ${{ matrix.scons-mono-flags }} ${{ inputs.lto }} ${{ env.MODULEFLAGS }}
          platform: linuxbsd
          target: ${{ matrix.target }}

      - name: Generate C# glue and solutions
        if: matrix.build-mono
        run:
          ./bin/godot.linuxbsd.editor.${{ env.BIN_ARCH }}.mono --headless --generate-mono-glue ./modules/mono/glue
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=linuxbsd --werror

      - name: Remove editor if template
        if: matrix.build-mono && matrix.target != 'editor'
        run:
          rm ./bin/godot.linuxbsd.editor.${{ env.BIN_ARCH }}.mono

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: linux-${{ matrix.target }}-${{ matrix.scons-flags }}-${{ inputs.lto }}
        continue-on-error: true

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.target }}-${{ matrix.scons-flags }}-${{ inputs.lto }}
          path: bin

  build-linux-arm64:
    runs-on: ubuntu-latest-arm
    container: almalinux:8
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Template (target=template_release, arch=arm64)
            target: template-release
            scons-flags: arch=arm64
            scons-mono-flags: ''
            build-mono: false

          - name: Template Mono (target=template_release, arch=arm64)
            target: template-release
            scons-flags: arch=arm64
            scons-mono-flags: ''
            build-mono: true

    steps:
      - name: Setup Linux environment
        run: |
          rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled powertools
          dnf update -y
          dnf install -y git pkgconfig tar bzip2 wget file
          if [[ "${{ matrix.target }}" == "editor" ]]; then
            dnf install -y gettext
          fi

      - name: Install dependencies
        run: |
          dnf install -y libatomic libatomic-static wayland-devel clang lld
          ln -s /usr/lib/gcc/aarch64-redhat-linux/8/libatomic.a /usr/lib/libatomic.a
          wget https://github.com/godotengine/buildroot/releases/download/godot-2023.08.x-4/aarch64-godot-linux-gnu_sdk-buildroot.tar.bz2
          tar -xjf aarch64-godot-linux-gnu_sdk-buildroot.tar.bz2 -C /opt
          /opt/aarch64-godot-linux-gnu_sdk-buildroot/relocate-sdk.sh
          export PATH=/opt/aarch64-godot-linux-gnu_sdk-buildroot/bin:$PATH
          echo "PATH=/opt/aarch64-godot-linux-gnu_sdk-buildroot/bin:$PATH" >> $GITHUB_PATH
          if [[ "${{ matrix.target }}" == "editor" ]]; then
            echo "MODULEFLAGS=${{ inputs.module_flags }}" >> $GITHUB_ENV
          else
            echo "MODULEFLAGS=${{ inputs.template_module_flags }}" >> $GITHUB_ENV
          fi

      - name: Install .NET SDK
        if: matrix.build-mono
        run: |
          dnf install -y dotnet-sdk-8.0

      - name: Free disk space on runner
        run: |
          echo "Disk usage before:" && df -h
          rm -rf /usr/local/lib/android
          echo "Disk usage after:" && df -h

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.tag }}
          submodules: recursive

      - name: Export Encryption Key
        if: ${{ inputs.use_encryption_key == 'true' }}
        run: echo "SCRIPT_AES256_ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> $GITHUB_ENV

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: linux-${{ matrix.target }}-${{ matrix.scons-flags }}-${{ inputs.lto }}

      - name: Editor compilation for glue
        uses: ./.github/actions/godot-build
        if: matrix.build-mono
        with:
          scons-flags: ${{ env.SCONSFLAGS }} ${{ matrix.scons-flags }} ${{ matrix.scons-mono-flags }} ${{ inputs.lto }} ${{ env.MODULEFLAGS }}
          platform: linuxbsd
          target: ${{ matrix.target }}

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} ${{ matrix.scons-flags }} ${{ matrix.scons-mono-flags }} ${{ inputs.lto }} ${{ env.MODULEFLAGS }}
          platform: linuxbsd
          target: ${{ matrix.target }}

      - name: Generate C# glue and solutions
        if: matrix.build-mono
        run:
          ./bin/godot.linuxbsd.editor.arm64.mono --headless --generate-mono-glue ./modules/mono/glue
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=linuxbsd --werror

      - name: Remove editor if template
        if: matrix.build-mono && matrix.target != 'editor'
        run:
          rm ./bin/godot.linuxbsd.editor.arm64.mono

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: linux-${{ matrix.target }}-${{ matrix.scons-flags }}-${{ inputs.lto }}
        continue-on-error: true

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.target }}-${{ matrix.scons-flags }}-${{ inputs.lto }}
          path: bin
